import type { ToolDef } from "./types";

const PDF = [".pdf"];

export const EDIT_TOOLS: ToolDef[] = [
  {
    slug: "pdf-editor",
    name: "Edit PDF",
    tagline: "The full visual workspace.",
    description:
      "A complete browser-based PDF editor: add text, draw freely, highlight, place shapes and images, sign, erase annotations, and undo/redo everything \u2014 then export a flattened, share-ready PDF.",
    category: "edit",
    icon: "\u270D\uFE0F",
    accept: PDF,
    mode: "editor",
    popular: true,
    keywords: ["edit pdf", "pdf editor online", "modify pdf"],
    steps: [
      "Open the editor and drop your PDF.",
      "Pick tools from the toolbar: text, draw, highlight, shapes, images.",
      "Move or delete anything with Select + Eraser; undo mistakes anytime.",
      "Export the edited PDF with all edits flattened onto the pages.",
    ],
    faqs: [
      {
        q: "Do edits change the original text?",
        a: "The editor overlays new content on your pages and flattens it on export \u2014 like marking up a printed copy. For rewording existing paragraphs, convert to Word first.",
      },
      {
        q: "Can I undo?",
        a: "Yes. Ctrl+Z / Ctrl+Y work, and toolbar Undo/Redo buttons track every action per session.",
      },
    ],
  },
  {
    slug: "add-text",
    name: "Add Text to PDF",
    tagline: "Type anywhere on the page.",
    description:
      "Place custom text anywhere on your PDF pages \u2014 labels, corrections, notes \u2014 using the visual editor's text tool with size and color controls.",
    category: "edit",
    icon: "\u{1F524}",
    accept: PDF,
    mode: "editor",
    editorPreset: "text",
    keywords: ["add text to pdf", "write on pdf", "pdf text tool"],
    steps: ["Upload your PDF.", "Choose the Text tool and click where you need it.", "Type your content.", "Export the finished PDF."],
    faqs: [],
  },
  {
    slug: "add-images",
    name: "Add Image to PDF",
    tagline: "Drop logos and photos onto pages.",
    description:
      "Insert PNG or JPG images onto any page, then drag to position and resize them before exporting a final PDF.",
    category: "edit",
    icon: "\u{1F5BC}\uFE0F",
    accept: PDF,
    mode: "editor",
    editorPreset: "image",
    keywords: ["add image to pdf", "insert logo in pdf"],
    steps: ["Upload the PDF.", "Select Image tool and pick a file.", "Drag and resize on the canvas.", "Export."],
    faqs: [],
  },
  {
    slug: "add-shapes",
    name: "Add Shapes to PDF",
    tagline: "Rectangles and circles, drawn to order.",
    description:
      "Annotate PDFs with clean rectangles and ellipses \u2014 box form fields, circle key data, build simple diagrams directly on the document.",
    category: "edit",
    icon: "\u2B1C",
    accept: PDF,
    mode: "editor",
    editorPreset: "shape",
    keywords: ["add shapes to pdf", "draw rectangle on pdf", "circle pdf"],
    steps: ["Upload your document.", "Choose Rectangle or Circle.", "Drag out the shape.", "Adjust color, then export."],
    faqs: [],
  },
  {
    slug: "highlight-pdf",
    name: "Highlight PDF",
    tagline: "Marker strokes over any passage.",
    description:
      "Add translucent highlighter strokes across important passages of your PDF, just like a physical marker but fully erasable before export.",
    category: "edit",
    icon: "\u{1F58D}\uFE0F",
    accept: PDF,
    mode: "editor",
    editorPreset: "highlight",
    keywords: ["highlight pdf", "pdf highlighter tool"],
    steps: ["Upload the PDF.", "Grab the Highlighter.", "Sweep over passages.", "Export highlighted copy."],
    faqs: [],
  },
  {
    slug: "draw-on-pdf",
    name: "Draw on PDF",
    tagline: "Freehand pen for natural markup.",
    description:
      "Sketch, underline and annotate with a smooth freehand pen in any color and thickness \u2014 ideal for reviews, tutoring and quick feedback.",
    category: "edit",
    icon: "\u{1F58B}\uFE0F",
    accept: PDF,
    mode: "editor",
    editorPreset: "pen",
    keywords: ["draw on pdf", "freehand pdf annotation", "pdf pen tool"],
    steps: ["Open your PDF.", "Pick Pen and a color/width.", "Draw naturally with mouse, pen or finger.", "Export when done."],
    faqs: [],
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    tagline: "Stamp ownership across every page.",
    description:
      "Apply text or image watermarks with full control over opacity, rotation, size, color and 9-position placement. Protect drafts, brand documents or mark confidential files.",
    category: "edit",
    icon: "\u{1F4A7}",
    accept: PDF,
    engine: "watermark",
    popular: true,
    keywords: ["watermark pdf", "add watermark to pdf", "stamp pdf"],
    steps: [
      "Upload the PDF.",
      "Choose text or image watermark and tune style settings.",
      "Apply to all pages or a selected range.",
      "Download the stamped document.",
    ],
    faqs: [
      { q: "Can I use my company logo?", a: "Yes \u2014 switch the watermark type to Image and upload a PNG (transparency supported) or JPG." },
      { q: "Is the watermark removable?", a: "It is flattened into page content on export, so casual removal isn't possible." },
    ],
    options: [
      {
        key: "watermarkType",
        label: "Type",
        type: "select",
        default: "text",
        options: [
          { value: "text", label: "Text" },
          { value: "image", label: "Image" },
        ],
      },
      { key: "text", label: "Text", type: "text", default: "CONFIDENTIAL", placeholder: "Watermark text" },
      { key: "imageFile", label: "Image", type: "file", accept: [".png", ".jpg", ".jpeg"] },
      { key: "opacity", label: "Opacity", type: "range", default: 0.18, min: 0.05, max: 1, step: 0.05 },
      { key: "rotation", label: "Rotation (\u00B0)", type: "range", default: 45, min: -90, max: 90, step: 15 },
      { key: "fontSize", label: "Size / scale", type: "range", default: 48, min: 12, max: 144, step: 4 },
      { key: "color", label: "Color", type: "color", default: "#6366f1" },
      {
        key: "position",
        label: "Position",
        type: "select",
        default: "center",
        options: [
          { value: "top-left", label: "Top left" },
          { value: "top-center", label: "Top center" },
          { value: "top-right", label: "Top right" },
          { value: "middle-left", label: "Middle left" },
          { value: "center", label: "Center" },
          { value: "middle-right", label: "Middle right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
      { key: "pages", label: "Pages (blank = all)", type: "text", placeholder: "e.g. 1-3" },
    ],
  },
];

export const SECURITY_TOOLS: ToolDef[] = [
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    tagline: "Password-lock sensitive documents.",
    description:
      "Encrypt a PDF with a password so only people you trust can open it. Permissions control printing, copying and modification. Encryption happens locally \u2014 your password never leaves the browser.",
    category: "security",
    icon: "\u{1F512}",
    accept: PDF,
    engine: "protect",
    popular: true,
    keywords: ["protect pdf", "password protect pdf", "lock pdf"],
    steps: [
      "Upload the PDF.",
      "Enter a strong password twice to confirm.",
      "PDFForge encrypts the document locally.",
      "Share the file and password through separate channels.",
    ],
    faqs: [
      {
        q: "Can the password be recovered?",
        a: "No. Store it safely \u2014 encryption is one-way by design.",
      },
      {
        q: "Which viewers support the output?",
        a: "Standard-compliant encryption opens in Adobe Reader, Preview, Chrome, Edge and mobile viewers.",
      },
    ],
    options: [
      { key: "password", label: "Password", type: "password", placeholder: "At least 4 characters" },
      { key: "confirm", label: "Confirm password", type: "password", placeholder: "Repeat password" },
      { key: "allowPrinting", label: "Allow printing", type: "checkbox", default: true },
      { key: "allowCopying", label: "Allow text copying", type: "checkbox", default: false },
    ],
  },
  {
    slug: "add-password",
    name: "Add Password",
    tagline: "Quick password gate for any PDF.",
    description:
      "The fastest way to require a password before a PDF opens. Same local encryption engine as Protect PDF with a streamlined single-field flow.",
    category: "security",
    icon: "\u{1F511}",
    accept: PDF,
    engine: "protect",
    keywords: ["add password to pdf", "require password pdf"],
    steps: ["Upload the PDF.", "Set and confirm your password.", "Encrypt locally.", "Download protected file."],
    faqs: [],
    options: [
      { key: "password", label: "Password", type: "password", placeholder: "New password" },
      { key: "confirm", label: "Confirm password", type: "password", placeholder: "Repeat password" },
    ],
  },
  {
    slug: "encrypt-pdf",
    name: "Encrypt PDF",
    tagline: "Strong encryption with permissions.",
    description:
      "Apply real encryption to your PDF with granular permissions \u2014 decide who may print, copy text or modify the document after opening.",
    category: "security",
    icon: "\u{1F6E1}\uFE0F",
    accept: PDF,
    engine: "protect",
    keywords: ["encrypt pdf", "pdf encryption", "secure pdf"],
    steps: ["Upload the document.", "Set passwords and permission toggles.", "Encryption runs in-browser.", "Download the encrypted PDF."],
    faqs: [],
    options: [
      { key: "password", label: "User password", type: "password" },
      { key: "ownerPassword", label: "Owner password (optional)", type: "password" },
      { key: "allowPrinting", label: "Allow printing", type: "checkbox", default: true },
      { key: "allowModifying", label: "Allow editing", type: "checkbox", default: false },
      { key: "allowCopying", label: "Allow copying", type: "checkbox", default: false },
    ],
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    tagline: "Remove passwords you own.",
    description:
      "Already authorized to open a password-protected PDF? Enter its password to produce an unlocked copy for easier reading and sharing. PDFForge never attempts to bypass encryption without the correct password.",
    category: "security",
    icon: "\u{1F513}",
    accept: PDF,
    engine: "unlock",
    popular: true,
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf"],
    steps: [
      "Upload the encrypted PDF.",
      "Type the password you use to open it.",
      "Pages are decrypted and rebuilt locally.",
      "Download the unlocked copy.",
    ],
    faqs: [
      {
        q: "Can you crack an unknown password?",
        a: "No \u2014 deliberately. Removing protection requires the correct password. This keeps the tool compliant and your documents safe.",
      },
      {
        q: "Why does the unlocked copy look slightly different?",
        a: "Decryption produces a high-quality flattened rebuild, which makes previously restricted text non-selectable but visually identical.",
      },
    ],
    options: [{ key: "password", label: "Current password", type: "password", placeholder: "Password used to open this PDF" }],
  },
];

export const OTHER_TOOLS: ToolDef[] = [
  {
    slug: "pdf-ocr",
    name: "PDF OCR",
    tagline: "Recognize text in scans \u2014 EN / UR / AR.",
    description:
      "Run optical character recognition on scanned PDFs entirely in your browser. Supports English, Urdu and Arabic, with a pluggable language system so more can be added. Edit recognized text before downloading.",
    category: "other",
    icon: "\u{1F50D}",
    accept: PDF,
    engine: "ocr",
    popular: true,
    keywords: ["pdf ocr", "scanned pdf to text", "arabic ocr", "urdu ocr"],
    steps: [
      "Upload a scanned PDF.",
      "Choose the document language.",
      "Tesseract OCR reads every page locally.",
      "Review, edit and download the extracted text.",
    ],
    faqs: [
      {
        q: "Where does OCR run?",
        a: "Fully in your browser via WebAssembly. The first run downloads the language model (~10\u201315 MB), which is cached for next time.",
      },
      {
        q: "How accurate is Urdu/Arabic recognition?",
        a: "Accuracy depends on scan quality. Clean 300-DPI scans perform best; noisy faxes may need cleanup.",
      },
      {
        q: "Can more languages be added?",
        a: "Yes \u2014 the engine accepts any Tesseract traineddata language code, so adding languages is a one-line registry change.",
      },
    ],
    options: [
      {
        key: "language",
        label: "Language",
        type: "select",
        default: "eng",
        options: [
          { value: "eng", label: "English" },
          { value: "urd", label: "Urdu" },
          { value: "ara", label: "Arabic" },
        ],
      },
      { key: "pages", label: "Pages (blank = all)", type: "text", placeholder: "e.g. 1-5" },
    ],
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    tagline: "Instant .txt extraction.",
    description:
      "Pull every piece of selectable text out of a PDF into a plain text file \u2014 fast, private and perfect for indexing, quoting or feeding other tools.",
    category: "other",
    icon: "\u{1F4DD}",
    accept: PDF,
    engine: "pdf-to-text",
    keywords: ["pdf to text", "extract text from pdf"],
    steps: ["Upload the PDF.", "Text extraction runs page by page.", "Review in the built-in editor.", "Download the .txt file."],
    faqs: [],
  },
  {
    slug: "extract-images",
    name: "Extract Images",
    tagline: "Every embedded image, unpacked.",
    description:
      "Harvest embedded raster images from inside a PDF and download them as PNG files bundled in a ZIP archive.",
    category: "other",
    icon: "\u{1F309}",
    accept: PDF,
    engine: "extract-images",
    keywords: ["extract images from pdf", "pdf image extractor"],
    steps: ["Upload the PDF.", "Embedded images are scanned page by page.", "Browse the gallery preview.", "Download all as ZIP."],
    faqs: [],
  },
  {
    slug: "page-numbers",
    name: "Add Page Numbers",
    tagline: "Classic numbering, flexible placement.",
    description:
      "Insert page numbers in nine positions with formats like \u201Cn\u201D, \u201CPage n\u201D or \u201Cn / N\u201D, custom starting numbers and optional cover-page skipping.",
    category: "other",
    icon: "\u{1F522}",
    accept: PDF,
    engine: "page-numbers",
    keywords: ["add page numbers to pdf", "pdf numbering"],
    steps: ["Upload the PDF.", "Pick format and position.", "Set start number if needed.", "Download numbered file."],
    faqs: [],
    options: [
      {
        key: "format",
        label: "Format",
        type: "select",
        default: "n",
        options: [
          { value: "n", label: "1, 2, 3" },
          { value: "n-of-total", label: "1 / N" },
          { value: "page-n", label: "Page 1" },
          { value: "page-n-of-total", label: "Page 1 of N" },
        ],
      },
      {
        key: "position",
        label: "Position",
        type: "select",
        default: "bottom-center",
        options: [
          { value: "top-left", label: "Top left" },
          { value: "top-center", label: "Top center" },
          { value: "top-right", label: "Top right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-center", label: "Bottom center" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
      { key: "startPage", label: "Start numbering at", type: "number", default: 1, min: 1, max: 5000 },
      { key: "fontSize", label: "Font size", type: "range", default: 10, min: 8, max: 16, step: 1 },
      { key: "skipFirst", label: "Skip cover page", type: "checkbox", default: false },
    ],
  },
  {
    slug: "sign-pdf",
    name: "Add Signature",
    tagline: "Draw, type or upload your signature.",
    description:
      "Sign documents digitally in three ways: draw with finger/mouse, type in a handwriting style, or upload a signature image. Place, resize and apply it to any page, then export.",
    category: "other",
    icon: "\u{1F58A}\uFE0F",
    accept: PDF,
    mode: "signature",
    popular: true,
    keywords: ["sign pdf", "add signature to pdf", "electronic signature"],
    steps: [
      "Create your signature by drawing, typing or uploading.",
      "Choose the target page.",
      "Click to position, drag corners to resize.",
      "Apply Signature and download the signed PDF.",
    ],
    faqs: [
      { q: "Is this a legal e-signature?", a: "Placed signatures are widely accepted for everyday agreements. For regulated workflows requiring certificates, use a dedicated CA-based signing service." },
    ],
  },
  {
    slug: "compare-pdf",
    name: "Compare PDFs",
    tagline: "Spot every difference instantly.",
    description:
      "Compare two PDFs line by line. PDFForge reports added and removed content with page references and generates a downloadable diff report.",
    category: "other",
    icon: "\u2696\uFE0F",
    accept: PDF,
    multiple: true,
    minFiles: 2,
    maxFiles: 2,
    engine: "compare",
    keywords: ["compare pdf", "pdf diff", "find differences between pdfs"],
    steps: ["Upload two versions of a document.", "Text is extracted and aligned.", "Differences are summarized live.", "Download the full report."],
    faqs: [],
  },
  {
    slug: "pdf-metadata",
    name: "Metadata Editor",
    tagline: "Own your document properties.",
    description:
      "Read and rewrite PDF metadata: title, author, subject and keywords. Clean tracking fields or set professional document properties before publishing.",
    category: "other",
    icon: "\u{1F4C1}",
    accept: PDF,
    engine: "metadata",
    keywords: ["pdf metadata editor", "change pdf author", "edit pdf properties"],
    steps: ["Upload the PDF.", "Fill in the properties you want to change.", "Metadata is written locally.", "Download updated file."],
    faqs: [],
    options: [
      { key: "title", label: "Title", type: "text", placeholder: "Leave blank to keep" },
      { key: "author", label: "Author", type: "text", placeholder: "Leave blank to keep" },
      { key: "subject", label: "Subject", type: "text", placeholder: "Leave blank to keep" },
      { key: "keywords", label: "Keywords (comma separated)", type: "text", placeholder: "report, 2026, finance", wide: true },
    ],
  },
];
